name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    name: Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup git
        run: 'git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"'
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: 'maven'
      - name: Apply patches
        run: './blueberry p'
      - name: Bake installer
        run: './blueberry i'
      - name: Retrieve Minecraft version
        run: 'echo "::set-output name=version::$(mvn -f pom.xml help:evaluate -Dexpression=minecraft.version -q -DforceStdout)"'
        id: retrieveMcVersion
      - name: Retrieve API version
        run: 'echo "::set-output name=version::$(mvn -f pom.xml help:evaluate -Dexpression=api.version -q -DforceStdout)"'
        id: retrieveApiVersion
      - name: Release new build
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ steps.retrieveMcVersion.outputs.version }}-${{ steps.retrieveApiVersion.outputs.version }}-${{ github.run_number }}
          files: '*-installer.jar'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: '~/.m2'
          key: maven
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: blueberry-installer-java-${{ matrix.java }}
          path: '*-installer.jar'
