name: Gradle CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    name: Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup git
        run: 'git config --global user.email "actions@github.com" && git config --global user.name "GitHub Actions"'
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: 'maven'
      - name: Update submodules
        run: "git submodule update --init && cd MagmaCube && git submodule update --init && cd .."
      - name: "Apply patches (MagmaCube)"
        run: './gradlew patchMinecraft --info --stacktrace'
      - name: "Apply patches (Blueberry)"
        run: './gradlew applyBlueberryPatches --info --stacktrace'
      - name: Bake installer
        run: './gradlew bakeInstaller --info --stacktrace'
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: '~/.m2'
          key: gradle-cache
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: blueberry-installer-java-${{ matrix.java }}
          path: '*-installer.jar'
